from app.schemas.ir import (
    CanvasIR,
    SemanticIR,
    SemanticStep,
    TargetIR,
    TargetFile,
    StepOrigin,
)


def transform_canvas_to_semantic(canvas_ir: CanvasIR, pipeline_name: str = "main_pipeline") -> SemanticIR:
    node_map = {node.id: node for node in canvas_ir.nodes}
    adj: dict[str, list[str]] = {node.id: [] for node in canvas_ir.nodes}
    in_degree: dict[str, int] = {node.id: 0 for node in canvas_ir.nodes}

    # Separate root level nodes from nested nodes attached to parent C-blocks
    root_nodes = [node for node in canvas_ir.nodes if not node.data.parent_id]

    for edge in canvas_ir.edges:
        if edge.source in adj and edge.target in in_degree:
            adj[edge.source].append(edge.target)
            in_degree[edge.target] += 1

    # Topological sort for execution order
    queue = [node.id for node in root_nodes if in_degree[node.id] == 0]
    ordered_ids: list[str] = []

    while queue:
        curr = queue.pop(0)
        ordered_ids.append(curr)
        for neighbor in adj.get(curr, []):
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0 and not node_map[neighbor].data.parent_id:
                queue.append(neighbor)

    # Helper function to build SemanticStep recursively
    def build_semantic_step(node) -> SemanticStep:
        data = node.data
        step = SemanticStep(
            step_id=node.id,
            name=data.label,
            step_type=data.node_type,
            namespace=data.namespace,
            func_name=data.func_name,
            origin=data.origin,
            params=data.params,
            contract=data.contract,
            condition_expression=data.condition_expression,
            for_iterations=data.for_iterations,
            merge_policy=data.merge_policy,
        )

        # Children nested inside IF_BODY slot
        if_children = [
            build_semantic_step(child)
            for child in canvas_ir.nodes
            if child.data.parent_id == node.id and child.data.slot_type in ("if_body", "loop_body", "parallel_body")
        ]
        # Children nested inside ELSE_BODY slot
        else_children = [
            build_semantic_step(child)
            for child in canvas_ir.nodes
            if child.data.parent_id == node.id and child.data.slot_type == "else_body"
        ]

        if data.node_type == "condition":
            step.branch_true = if_children
            step.branch_false = else_children
        elif data.node_type == "for":
            step.loop_steps = if_children
        elif data.node_type == "parallel":
            step.parallel_steps = if_children

        return step

    steps: list[SemanticStep] = []
    global_reads: set[str] = set()
    global_writes: set[str] = set()

    for node_id in ordered_ids:
        node = node_map[node_id]
        step = build_semantic_step(node)
        steps.append(step)

        global_reads.update(node.data.contract.reads)
        global_writes.update(node.data.contract.writes)

    return SemanticIR(
        pipeline_name=pipeline_name,
        steps=steps,
        global_context_reads=sorted(list(global_reads)),
        global_context_writes=sorted(list(global_writes)),
    )


def transform_semantic_to_target(semantic_ir: SemanticIR, project_name: str = "wpipe_microservice") -> TargetIR:
    imports: list[str] = ["from wpipe import Pipeline, step"]
    step_declarations: list[str] = []

    for idx, s in enumerate(semantic_ir.steps):
        if s.step_type == "step":
            if s.namespace and s.func_name:
                imports.append(f"from {s.namespace} import {s.func_name}")
                step_declarations.append(f"        {s.func_name}()")
            else:
                func_safe = s.name.lower().replace(" ", "_")
                step_declarations.append(f"        {func_safe}_step")
        elif s.step_type == "condition":
            expr = s.condition_expression or "True"
            step_declarations.append(f"        # Condition: {expr}")
        elif s.step_type == "parallel":
            step_declarations.append(f"        # Parallel policy: {s.merge_policy}")

    imports_str = "\n".join(set(imports))
    steps_str = ",\n".join(step_declarations)

    pipeline_code = f"""# Generated by WPipe Studio
{imports_str}

def build_pipeline() -> Pipeline:
    pipe = Pipeline(name="{semantic_ir.pipeline_name}")
    pipe.set_steps([
{steps_str}
    ])
    return pipe

if __name__ == "__main__":
    pipe = build_pipeline()
    result = pipe.run()
    print("Pipeline completed successfully:", result)
"""

    main_code = """from fastapi import FastAPI
from app.pipelines import build_pipeline

app = FastAPI(title="WPipe Microservice", version="1.0.0")

@app.get("/health")
def health():
    return {"status": "ok"}

@app.post("/run")
def run_pipeline(payload: dict | None = None):
    pipe = build_pipeline()
    result = pipe.run(payload or {})
    return {"status": "success", "result": result}
"""

    dockerfile = """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python3", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

    makefile = """help:
\t@echo "Available commands: install, dev, test, lint, format"

install:
\tpip install -r requirements.txt

dev:
\tuvicorn app.main:app --reload

test:
\tpytest app/tests/ -q

lint:
\truff check app/

format:
\truff format app/
"""

    readme = f"""# {project_name}

Microservicio Python auto-generado por **WPipe Studio**.

## Tecnologías y Librerías Principales
- **FastAPI**: Framework web asíncrono para exponer endpoints HTTP.
- **WPipe**: Motor de orquestación de pipelines y flujos de trabajo.
- **Uvicorn**: Servidor ASGI de alto rendimiento.
- **Pytest**: Suite de pruebas unitarias automatizadas.

## Cómo ejecutar los tests
```bash
pytest app/tests/ -q
```
"""

    test_code = """from app.pipelines import build_pipeline

def test_pipeline_builds():
    pipe = build_pipeline()
    assert pipe is not None
    assert pipe.name == "main_pipeline"
"""

    files = [
        TargetFile(path="app/pipelines.py", content=pipeline_code),
        TargetFile(path="app/main.py", content=main_code),
        TargetFile(path="app/tests/test_pipelines.py", content=test_code),
        TargetFile(path="Dockerfile", content=dockerfile),
        TargetFile(path="Makefile", content=makefile),
        TargetFile(path="requirements.txt", content="fastapi\nuvicorn\nwpipe\npytest\nruff\n"),
        TargetFile(path="README.md", content=readme),
    ]

    return TargetIR(project_name=project_name, files=files)
